[settings]
experimental = true # To enable installation of Go tools from source with mise.

[tools]
golangci-lint = '2.6.2'
goreleaser = '2.3.2'
oapi-codegen = '2.4.1'
skaffold = '2.16.1'
kustomize = '5.8.0'
