apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: kv
  replicas: 1
  template:
    metadata:
      labels:
        app: kv
    spec:
      containers:
        - name: app
          image: ghcr.io/kumahq/kuma-counter-demo:latest
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.mesh-observability:4317
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          ports:
            - name: http
              containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: kv
  namespace: kuma-demo
spec:
  selector:
    app: kv
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: kuma-demo
  labels:
    app: demo-app
    version: v1
spec:
  selector:
    matchLabels:
      app: demo-app
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
        - name: app
          image: ghcr.io/kumahq/kuma-counter-demo:latest
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.mesh-observability:4317
            - name: KV_URL
              value: "http://kv.kuma-demo.svc.cluster.local:5050"
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          ports:
            - name: http
              containerPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-v2
  namespace: kuma-demo
  labels:
    app: demo-app
    version: v2
spec:
  selector:
    matchLabels:
      app: demo-app
      version: v2
  replicas: 0
  template:
    metadata:
      labels:
        app: demo-app
        version: v2
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/kumahq/kuma-counter-demo:latest
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.mesh-observability:4317
            - name: KV_URL
              value: "http://kv.kuma-demo.svc.cluster.local:5050"
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          ports:
            - name: http
              containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: kuma-demo
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    appProtocol: http
    port: 5050
    targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-v1
  namespace: kuma-demo
spec:
  selector:
    app: demo-app
    version: v1
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5050
      targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-v2
  namespace: kuma-demo
spec:
  selector:
    app: demo-app
    version: v2
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5050
      targetPort: 5050
