name: CI
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - next
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - run: make clean
      - run: make generate
      - run: make check
      - name: check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git status
            git diff
            echo "Files have changed, failing CI"
            exit 1
          fi
      - run: make build
      - run: make test
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: builds
          path: |
            dist/*.tar.gz
            dist/metadata.json
            dist/config.yaml
            dist/artifacts.json
            dist/*_checksums.txt
          retention-days: 5
